Koble/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Koble.Areas.Admin.Controllers
{
    public class CategoryController : Controller
    {
        //
        // GET: /Admin/Category/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Koble/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Koble.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        //
        // GET: /Admin/Dashboard/

        public ActionResult Index()
        {
            return View();
        }
    }
}

Koble/Areas/Admin/Views/Category/Index.cshtml
@{
    ViewBag.Title = "CategoryList";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@* Scipts / CSS *@
<link href="~/Content/css/plugins/jasny/jasny-bootstrap.css" rel="stylesheet" />
<script src="~/Content/js/plugins/jstree/jstree.js"></script>
<script src="~/Content/js/plugins/jasny/jasny-bootstrap.js"></script>
<link href="~/Content/js/plugins/jstree/jstree.min.css" rel="stylesheet" />
<script src="~/Areas/Admin/Content/js/page/CategoryListPage.js"></script>
@* Scipts / CSS *@

<div class="row">
    <div class="col-md-4">
        <div class="block">
            <!-- Horizontal Form Title -->
            <div class="block-title">
                <h2><strong>Category List</strong></h2>
            </div>
            <form onsubmit="return false;" class="form-horizontal form-bordered" method="post" action="page_forms_general.html" style="min-height:647px;">
                <div id="CategoryTree">
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-8">
        <div class="block">
            <!-- Horizontal Form Title -->
            <div class="block-title">
                <div class="block-options pull-right">
                    <a title="" class="btn btn-alt btn-sm btn-default hidden" onclick="AddNewParent();" data-original-title="Add New Parent" id="NewParent"><i class="fa fa-user"></i> Add New Parent</a>
                    <a title="" class="btn btn-alt btn-sm btn-default hidden" onclick="AddNewChild()" data-original-title="Add New Child" id="NewChild"><i class="fa fa-users"></i> Add New Child</a>
                    <a title="" class="btn btn-alt btn-sm btn-default hidden" onclick="DeleteNode()" data-original-title="Delete" id="DeleteNode"><i class="fa fa-trash"></i> Delete</a>
                </div>
                <h2><strong>Actions</strong></h2>
            </div>
            <!-- END Horizontal Form Title -->
            <!-- Horizontal Form Content -->
            <form onsubmit="return false;" id="Category_Form" class="form-horizontal form-bordered" method="post" action="page_forms_general.html">
                <div class="form-group">
                    <label for="example-hf-email" class="col-md-3 control-label">Category Name *</label>
                    <div class="col-md-9">
                        <input type="text" placeholder="CategoryName" class="form-control" name="example-hf-email" id="CategoryName">
                    </div>
                </div>
                <div class="form-group">
                    <label for="example-textarea-input" class="col-md-3 control-label">Description</label>
                    <div class="col-md-9">
                        <textarea placeholder="Type Description Here.." class="form-control" rows="9" name="example-textarea-input" id="Description"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label for="example-select" class="col-md-3 control-label">Unit Type</label>
                    <div class="col-md-9">
                        <select size="1" class="form-control" name="example-select" id="UnitType">
                            <option value="0">Please select Unit Type</option>
                            <option value="1">Kg</option>
                            <option value="2">Ltr</option>
                            <option value="3">Packet</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="example-textarea-input" class="col-md-3 control-label">Category Image</label>
                    <div class="col-md-9">
                        <div id="customize_fileinput" data-provides="fileinput" class="fileinput fileinput-new">
                            <div class="fileinput-new thumbnail" id="DefaultImage">
                                <img class="m-t-xs img-responsive" style="max-height:200px;max-width:200px;" alt="..." src="~/Content/img/no_image.jpg">
                            </div>
                            <div id="ImageUrl" style="max-height:200px;max-width:200px;" class="fileinput-preview fileinput-exists thumbnail"></div>
                            <div>
                                <span class="btn btn-primary btn-file btn-xs"><span class="fileinput-new" id="SelectImage">Select image</span><span class="fileinput-exists">Change</span><input type="hidden" value="" name="..."><input type="file" name=""></span>
                                <a data-dismiss="fileinput" class="btn btn-warning fileinput-exists btn-xs" href="#">Remove</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group form-actions">
                    <div class="pull-right" style="margin-right:15px;">
                        <button class="btn btn-sm btn-primary" type="submit" id="save"><i class="fa fa-save"></i> Submit</button>
                        <button class="btn btn-sm btn-warning" type="reset" id="cancel" onclick="ResetAll();"><i class="fa fa-repeat"></i> Cancel</button>
                    </div>
                </div>
            </form>
            <!-- END Horizontal Form Content -->
        </div>
    </div>
</div>

Koble/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    <script src="@Url.Content("~/Content/js/vendor/modernizr-respond.min.js")"></script>
    <script src="@Url.Content("~/Content/js/vendor/jquery-1.11.3.min.js")"></script>
    <script src="@Url.Content("~/Content/js/vendor/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Content/js/common.js")"></script>
</head>
<body>
   
    <div id="page-wrapper">
        <!-- Page Container -->
        <div id="page-container" class="sidebar-partial sidebar-visible-lg sidebar-no-animations">
            @RenderPage("~/Areas/Admin/Views/Shared/_sidebarmenu.cshtml")
            <!-- Main Container -->
            <div id="main-container">
                <!-- Header -->
                <!-- In the PHP version you can set the following options from inc/config file -->
                <!--
                Available header.navbar classes:

                'navbar-default'            for the default light header
                'navbar-inverse'            for an alternative dark header

                'navbar-fixed-top'          for a top fixed header (fixed sidebars with scroll will be auto initialized, functionality can be found in js/app.js - handleSidebar())
                    'header-fixed-top'      has to be added on #page-container only if the class 'navbar-fixed-top' was added

                'navbar-fixed-bottom'       for a bottom fixed header (fixed sidebars with scroll will be auto initialized, functionality can be found in js/app.js - handleSidebar()))
                    'header-fixed-bottom'   has to be added on #page-container only if the class 'navbar-fixed-bottom' was added
                -->
                @RenderPage("~/Areas/Admin/Views/Shared/_header.cshtml")
                <!-- END Header -->
                <!-- Page content -->
                <div id="page-content">
                    @RenderBody()
                </div>
                <!-- END Page Content -->
                <!-- Footer -->
                @RenderPage("~/Areas/Admin/Views/Shared/_footer.cshtml")
                <!-- END Footer -->
            </div>
            <!-- END Main Container -->
        </div>
        <!-- END Page Container -->

        <!-- Scroll to top link, initialized in js/app.js - scrollToTop() -->
        <a href="#" id="to-top"><i class="fa fa-angle-double-up"></i></a>
        

        <!-- Remember to include excanvas for IE8 chart support -->
        <!--[if IE 8]><script src="~/Content/js/helpers/excanvas.min.js"></script><![endif]-->
    </div>
    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

Koble/Areas/Admin/Views/Shared/_footer.cshtml
<footer class="clearfix">
    <div class="pull-right">
        Crafted with <i class="fa fa-heart text-danger"></i> by <a href="#" target="_blank">techinfoplace</a>
    </div>
    <div class="pull-left">
        <span id="year-copy"></span> &copy; <a href="#" target="_blank">techinfoplace</a>
    </div>
</footer>

Koble/Areas/Admin/Views/Shared/_header.cshtml
<header class="navbar navbar-default">
    <!-- Left Header Navigation -->
    <ul class="nav navbar-nav-custom">
        <!-- Main Sidebar Toggle Button -->
        <li>
            <a href="javascript:void(0)" onclick="App.sidebar('toggle-sidebar');this.blur();">
                <i class="fa fa-bars fa-fw"></i>
            </a>
        </li>
        <!-- END Main Sidebar Toggle Button -->
        <!-- Template Options -->
    </ul>
    <!-- END Left Header Navigation -->
    <!-- Search Form -->
    <form action="javascript:void(0)" method="post" class="navbar-form-custom" role="search">
        <div class="form-group">
            <input type="text" id="top-search" name="top-search" class="form-control" placeholder="Search..">
        </div>
    </form>
    <!-- END Search Form -->
    
</header>

Koble/Areas/Admin/Views/Shared/_sidebarmenu.cshtml
@{
    string area = ViewContext.RouteData.DataTokens["area"].ToString().ToLower();
    string controller = ViewContext.RouteData.Values["controller"].ToString().ToLower();
    string action = ViewContext.RouteData.Values["Action"].ToString().ToLower();
}
<!-- Main Sidebar -->
<div id="sidebar">
    <!-- Wrapper for scrolling functionality -->
    <div id="sidebar-scroll">
        <!-- Sidebar Content -->
        <div class="sidebar-content">
            <!-- Brand -->
            <a href="index.html" class="sidebar-brand">
                <i class="gi gi-flash"></i><span class="sidebar-nav-mini-hide"><strong>Koble</strong></span>
            </a>
            <!-- END Brand -->
            <!-- User Info -->
            <div class="sidebar-section sidebar-user clearfix sidebar-nav-mini-hide">
                <div class="sidebar-user-avatar">
                    <a href="#">
                        <img src="~/Content/img/placeholders/avatars/avatar2.jpg" alt="avatar">
                    </a>
                </div>
                <div class="sidebar-user-name">Jhon Doe.</div>
                <div class="sidebar-user-links">
                    <a href="javascript:void(0)" data-toggle="tooltip" data-placement="bottom" title="Profile"><i class="gi gi-user"></i></a>
                    <a href="javascript:void(0)" data-toggle="tooltip" data-placement="bottom" title="Messages"><i class="gi gi-envelope"></i></a>
                    <!-- Opens the user settings modal that can be found at the bottom of each page (page_footer.html in PHP version) -->
                    <a href="javascript:void(0)" class="enable-tooltip" data-placement="bottom" title="Settings"><i class="gi gi-cogwheel"></i></a>
                    <a href="@Url.Action("Index", "login")" data-toggle="tooltip" data-placement="bottom" title="Logout"><i class="gi gi-exit"></i></a>
                </div>
            </div>
            <!-- END User Info -->
            <!-- Sidebar Navigation -->
            <ul class="sidebar-nav">
                <li>
                    <a href="@Url.Action("Index", "Dashboard")" class="@((controller == "dashboard" && action == "index")? "active" : "")"><i class="gi gi-stopwatch sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Dashboard</span></a>
                    <a href="@Url.Action("Index", "Category")" class="@((controller == "category" && action == "index") ? "active" : "")"><i class="gi gi-notes_2 sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Category</span></a>
                </li>
            </ul>
            <!-- END Sidebar Navigation -->
        </div>
        <!-- END Sidebar Content -->
    </div>
    <!-- END Wrapper for scrolling functionality -->
</div>
<!-- END Main Sidebar -->

Koble/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>